### ISSUE TITLE
Add "versions" for all "files" with Nextcloud WebDav API

### ISSUE THREAD

**Issue by mrustl** [KWB-R/kwb.nextcloud#8]
Versions are labeled by "datetime" in Nextcloud: 
Idea: add version integer for all "versions" (starting with "1" for oldest version).

**Comment by hsonne** [comment]
I implemented a function `get_version_info()` to check for avaliable versions by file ID
(2eb22ab950e0714626db40d120b62981c746c597):
```
file_info <- kwb.nextcloud:::list_files(
  path = "departments/urban-systems",
  pattern = "xlsx$", recursive = TRUE, max_depth = 1, full_info = TRUE
)

version_info <- kwb.nextcloud:::get_version_info(info$fileid[! info$isdir])

merge(file_info[, c("file", "fileid")], version_info, all.x = TRUE)
```

Result:
```
  fileid                             file version     getlastmodified    getetag
1  75632       Kontaktliste_Team_SUW.xlsx       1 2020-04-21 14:05:53 1587477953
2 104851 Urlaub_Team_Stand_April2020.xlsx       1 2020-04-21 19:42:04 1587498124
3 104851 Urlaub_Team_Stand_April2020.xlsx       2 2020-05-20 11:01:03 1589972463
4 114749        Preparation-good-bye.xlsx       1 2020-05-12 13:16:58 1589289418
5 114749        Preparation-good-bye.xlsx       2 2020-05-15 22:01:59 1589580119
6 114749        Preparation-good-bye.xlsx       3 2020-05-19 18:10:14 1589911814
7 114749        Preparation-good-bye.xlsx       4 2020-05-22 11:54:35 1590148475
```

**Comment by mrustl** [comment]
Looks awesome!

**Comment by hsonne** [comment]
Feel free to give me a rocket!

**Comment by hsonne** [comment]
Download is possible, by passing the hrefs returned by `get_version_info()` to `download_files()`.
Unfortunately, the files (and folders if versions of different files are addressed) are named according to the file IDs and timestamps associated with the versions (number of seconds since 1970). See example in 
https://github.com/KWB-R/kwb.nextcloud/blob/584e7f878ef032654d2289d8198f560af9fbb096/R/.test_put-delete.R#L65
